tessel/t2-firmware

boot/main.c, common/board.h, firmware/firmware.h, firmware/main.c, firmware/usb.c
rails should come up according to the following:
* 3.3V
* 800uS Delay
* 1.8V
* 50ms Delay
* PORST
Added a 200ms delay at the beginning because we can't control the rails right as they come up. Alternative is to shut down the SoC and bring it up again according to those delays.
=> Boot delay

test_rig/dap_hid.c, test_rig/test_rig.h, test_rig/usb.c
So all state gets reset between processes
Requires a corresponding change to t2-test-rig-sw
=> testrig: Put the SWD adaptor on a non-default altsetting

boot/main.c, common/hw.h, firmware/usb.c, scripts/boot.py
Abuse the WDT as a delayed reset source that sets a telltale bit in
RCAUSE. Add a vendor request to trigger a WDT reset.
=> Enter bootloader on USB command

node/tessel.js
This PR adds the ability to blink the four LEDs on T2. There are a couple of things to note:
1. With Tessel 1, the LEDs were also part of the PIN class because they could utilize the same sort of interrupt functionality. That's not the case here so I made a distinct `LED` class 
2. There are some LED properties/methods from T2 that aren't implemented here because they don't make sense like pull resistors.
3. I added a `color` property because I thought that would be useful for some people.
4. I'm not sure how using these LEDs will affect any pre-existing triggers (like WLAN) or how to change them back if that is the case.
5. The old API returned an instance of the Pin object to change calls. I didn't do that here because all of the calls are async. We could consider making sync versions …
=> Adds basic LED functionality

node/tessel.js
If the component doesn't support the operation, just eliminate the method.
=> Remove Led.prototype.input

node/tessel.js
Fixes:
```
tessel.js
24 |    ]
^ Missing semicolon.
41 |        console.log('sock err', e)
^ Missing semicolon.
42 |    })
^ Missing semicolon.
46 |    })
^ Missing semicolon.
51 |        replyBuf = Buffer.concat([replyBuf, this.sock.read()])
^ Missing semicolon.
53 |        while (replyBuf.length != 0) {
^ Expected '!==' and instead saw '!='.
55 |            if (byte == REPLY.ASYNC_UART_RX) {
^ Expected '===' and instead saw '=='.
75 |                    if (mode == 'low' || mode == 'high') {
^ Expected '===' and instead saw '=='.
75 |                    if (mode == 'low' || mode == 'high') {
^ Expected '===' and instead saw '=='.
84 |                if (this.replyQueue.length == 0) {
^ Expected '===' and instead saw '=='.
90 |                if (byte == REPLY.DATA) {
^ Expected '===' …
```
=> Enforce jshint rules: passing (Order: 1)

node/tessel.js, node/test/unit/tessel.js
Blocked by https://github.com/tessel/t2-firmware/pull/58
Once that lands, this will apply cleanly
=> Ensure that port.I2C can produce a fresh instance of I2C. (Order: 4)

node/tessel.js, node/test/unit/tessel.js, node/tests/interrupt.js
Blocked by #64 
Once #64 lands, I will rebase this branch to prepare for merging. 
Smoke tests completed: 
- interrupts on port A pins 2, 5, 6, 7
- interrupts on port B pins 2, 5, 6, 7
The only changes relevant to this specific issue are https://github.com/rwaldron/t2-firmware/commit/0368d980ef33f53163692041bde67e16701b0a67
=> Make Port a subclass of EventEmitter. Fixes gh-65

node/tessel-export.js
Fixes #95 
It appears OpenWRT sets the default pixel value to 255 to mean "off". This change just catches that initial behaviour to match '0' being off.
=> Set OpenWRT default pixel value 255 to be logically false

node/tessel-export.js
This fixes the callbacks so as to throw an error if an error occurred and no callback was given.
It also allows any range between 0 and 255 inclusively for the led value, see discussion in #96.
=> fix callbacks in led

node/tessel-export.js, node/test/unit/tessel.js
We were clearing the interruptMode of a pin when there were still listeners attached for that mode.
- Event.listenerCount is now depreciated in node 4.x.x
- Tessel.Pin tests were sharing a socket between port a and port b when the tests didn't expect it
- Expand Tessel.Pin tests for other interrupts
=> Fix a bug when calling removeListener add some tests

boot.mk, common/samd21g18a_firmware_partition.ld, firmware.mk, firmware/bridge.c, firmware/usbpipe.c, soc/spid.c, soc/usbexecd.c, test_rig.mk
Adding this channel disable endpoint essentially lets the CLI reset the state of the USB Daemon each time it's used.
The downside is that we definitely will not be able to have a Tessel being used programmatically by multiple scripts at once over USB because the second one would cancel any ongoing USB comms the first one had going for it.
=> Fixes to reset USB Daemon state reliably

boot.mk, common/samd21g18a_firmware_partition.ld, firmware.mk, firmware/bridge.c, firmware/usbpipe.c, soc/spid.c, soc/spid.sh, soc/usbexecd.c, soc/usbexecd.sh, test_rig.mk
Fixes https://github.com/tessel/t2-firmware/issues/132.
So far I investigated how to create a domain socket that will act as a server using `epoll` and how to create a domain socket that will act as a client using `poll`. The reason we're using two different types of non-blocking polling is because the usb daemon could have an unknown number of concurrent connections and `epoll` is more efficient because the mechanics allow you to check only those events that fired. `poll`, on the other hand, is better for the SPI Daemon because it will always have four possible file descriptors (IRQ, USB Daemon, MOD PORT A, MOD PORT B) and the interface is somewhat simpler.
The snippets below basically have the usb daemon waiting for a new connection, accepting a new socket (the spi daemon), reading 4 …
=> Modifies USBDaemon to act as a server

firmware/usb.c
A simple request to determine if OpenWRT is booted or not via a transfer request (so you don't need to claim the device).
=> Allows for a transfer request to determine boot state

node/tessel-export.js, node/test/unit/tessel.js
The remaining migrations to RangeError are in the i2c-frequency-range branch
=> Use RangeError where appropriate. Fixes gh-156

node/tessel-export.js, node/test/unit/tessel.js
A follow-up build to #140, adding a Network Access Point (AP) API. 
TODO:
===
Proposed API:
**Methods**
- `configObject` contains the following properties: ssid (required), password, security (wpa, psk, psk2, none)
- default security is 'none', if there is a password in config then default security is 'psk2'
**Events**
Each event contains a settings object. 
- create: access point has been created
- on: access point has been enabled
- off: access point has been disabled
- reset: access point is about to reset
- error: an error occurred
**Concerns:**
Maybe check ap config rather than assuming it pre-exists ([match this logic in t2-cli](https://github.com/tessel/t2-cli/blob/master/lib/tessel/access-point.js#L147-L176)). This was added to t2-cli to support Tessel users who had not yet …
=> Adds Tessel access point API

node/tessel-export.js
New more informative error message if you try to call an interrupt on a pin which doesn't support it. Now users receiving this message have something actionable to do.
=> fixes https://github.com/tessel/t2-firmware/issues/71

node/tessel-export.js, node/test/unit/tessel.js
This allows multiple listeners to be used... `.on('rise')`, `.on('fall')` and `.on('change')` can all be used simultaneously.
See [Issue-69](https://github.com/tessel/t2-firmware/issues/69)
=> emit 'rise' and 'fall' events along with 'change' event

firmware/usb.c
Apply the Windows Compatible ID descriptor to the CDC interfaces
as well as the vendor-class interface. It seems that Windows will
only automatically install the driver if *all* interface of the device
have the WCID descriptor set to WINUSB.
This will prevent the CDC serial console interface from working on
Windows.
Bumps the bcdDevice so Windows machines that have cached the descriptors
will re-load them.
=> Make Windows auto-install WinUSB driver.

node/tessel-export.js, node/test/unit/tessel.js, node/tests/dac.js
See #175.
* Updated `.analogRead()` and `.analogWrite()` to operate on a 0-1 scale.
* Updated tests to account for new range.
* Fixed typo.
I noticed there are no unit tests for `.analogRead()` so maybe we should add some along with this change.
@rwaldron
=> Update analog read write range

node/package.json, node/tessel-export.js, node/test/unit/tessel.js
Fixes #178 - get connection info from system instead of in-memory cache
Fixes #190 - normalize security value on connection settings to match the standard configuration values, i.e. `none`, `wep`, `psk`, `psk2`
Fixes #192 - set a usable value to the connection `ip` property as opposed to of the seemingly random array of strings as `ips`.
This build changes how the `Wifi.connection` method works, making it an asynchronous request to the system requiring a `callback` argument to return the network settings. This will require a change of the documentation before releasing to the public, with a reference to that release version this change was made.
```js
tessel.network.wifi.connection(callback);
function callback (error, networkSettings) {
if (error) { throw error; } …
```
=> Wifi.connection(): Fetch network settings, normalize values

common/hw.h, firmware/main.c
Use the SAMD21 POR routine to cleanly & deterministically reset the board
=> Implements button reset

node/tessel-export.js, node/test/unit/tessel.js
- Closes ports before executing `reboot`
1. Pull this branch local
2. With a T2 connected via LAN, run: 
```
scp -i /PATH/TO/t2-firmware/node/tessel-export.js root@[NAME OF YOUR TESSEL].local:/usr/lib/node/tessel-export.js
```
(make the appropriate changes)
3. Create a new project: 
```
t2 init
```
4. Paste this into `index.js`: 
```js
var tessel = require("tessel");
// Turn one of the LEDs on to start.
tessel.led[2].on();
// Blink!
setInterval(function () {
tessel.led[2].toggle();
tessel.led[3].toggle();
}, 100);
console.log("I'm blinking! (Press CTRL + C to stop)");
console.log("In 2 seconds, I will reboot this Tessel.");
setTimeout(() => tessel.reboot(), 2000);
```
Expected outcome: 
```
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bruno.
INFO Building project. …
```
=> Implements Tessel.prototype.reboot(). Closes gh-188

node/tessel-export.js, node/test/unit/tessel.js
Fixes #219 
**Smoke test:**
Push the new node module to your Tessel using `scp`, [check out this gist](https://gist.github.com/HipsterBrown/d0d24e9e1867ef4e5bb3) to learn more. 
- `mkdir t2-test && cd t2-test`
- `t2 init`
- Connect your Tessel to a wifi network
- Replace the contents of the `index.js` file with the following:
```
tessel.network.wifi.connection(console.log.bind(console));
```
- `t2 run index.js`
You should get output like the following:
```
INFO Looking for your Tessel...
INFO Connected to tessel-router.
INFO Building project.
INFO Writing project to RAM on tessel-router (226.816 kB)...
INFO Deployed.
INFO Running test.js...
null { phy: 'phy0',
ssid: 'Speak Friend',
bssid: '54:E4:3A:E8:A0:1C',
country: '00',
mode: 'Client',
channel: 6, …
```
=> Get correct address from wifi connection data

node/tessel-export.js, node/test/unit/tessel.js
=> Make all calls to Tessel.LED.prototype.write() pass 1 or 0 as an argument. Fixes gh-221

.travis.yml
As we prepare for a release of t2-firmware to support Node 8, this PR adds that version to our Travis CI configuration.
=> Travis: add Node 8, remove Node 5

node/tessel-export.js, node/test/unit/tessel.js
We've been successfully running the UART at 230400 baud on hundreds of Tessels for a few years now, would be lovely to include support for this in the official firmware.  This pull request simply extends the max value from 115200 to 230400 baud.
=> Extended maximum UART baud rate from 115200 to 230400

firmware/port.c
I was getting this error building the firmware on a Mac OS X Mojave Beta:
```
/var/folders/5n/kqr_3l4d3n56b9s1xlvh_tsr0000gn/T//ccIS8P05.ltrans0.ltrans.o: In function `port_step':
/Users/nodebotanist/Code/bots/tessel/t2-firmware/firmware/port.c:683: undefined reference to `port_async_events_allowed'
/var/folders/5n/kqr_3l4d3n56b9s1xlvh_tsr0000gn/T//ccIS8P05.ltrans0.ltrans.o: In function `port_handle_sercom_uart_i2c':
/Users/nodebotanist/Code/bots/tessel/t2-firmware/firmware/port.c:775: undefined reference to `port_async_events_allowed'
collect2: error: ld returned 1 exit status
make: *** [build/firmware.elf] Error 1
```
When I made this change, it started working correctly. Not entirely sure why...?
Note: ran on High Sierra, still worked and built.
=> I don't know why, but this fixes the build
