- common/clock.c
- common/hw.h
- common/sercom.c
- firmware/bridge.c
- firmware/firmware.h
- firmware/main.c
- firmware/port.c
- firmware/usbserial.c
- node/tessel.js
- node/tests/spi.js
Can now go between 24Mhz and 368hz.
This commit makes v2 work with the ambient module.
> Adds ability to change spi clock speeds

- .gitignore
- scripts/usbdaemon_test/Cargo.lock
- scripts/usbdaemon_test/Cargo.toml
- scripts/usbdaemon_test/README.md
- scripts/usbdaemon_test/src/lib.rs
- scripts/usbdaemon_test/testcase/multiple_processes
- scripts/usbdaemon_test/testcase/open_process
- scripts/usbdaemon_test/testcase/out_of_order_close
- scripts/usbdaemon_test/usbdaemon_test.rs
- soc/Makefile
- soc/usbexecd.c
- soc/usbexecd.sh
I'll remove all of the extraneous logs before it's ready to be merged.
> USB Daemon

- common/hw.h
- common/timer.c
- firmware/firmware.h
- firmware/port.c
@jiahuang, please see the commit messages
> Fixes to UART branch

- soc/usbexecd.c
> [WIP] Fixes USBDaemon crash on large child process writes

- common.mk
- common/analog.c
- common/board.h
- common/hw.h
- firmware/main.c
- firmware/port.c
- node/tessel.js
- node/tests/adc.js
- node/tests/dac.js
clean commit of analog functionality
> adding analog

- common/analog.c
The key part of the diff:
```.diff
-    while(ADC->INTFLAG.reg & ADC_INTFLAG_RESRDY);
+    while(!(ADC->INTFLAG.reg & ADC_INTFLAG_RESRDY));
```
> Fix analog_read

- common/hw.h
- firmware/firmware.h
- firmware/flash.c
- scripts/flash.py
This cuts 90 seconds off the flash write time.
> Optimize flash write

- README.md
@johnnyman727 does this look correct to you? This as a bare minimum; will add specifics of port/pin docs too
> adds ToC and hardware API docs

- node/tessel.js
`unshift` triggers `readable` immediately, so a split packet would lead
to infinite recursion. Instead, manage the buffer of partial replies
manually.
Tested with climate example on io.js 2.0.2, which previously triggered this bug, and with tests/uart.js to test the UART_ASYNC_RX code path.
> tessel.js: Fix infinite recursion (RangeError) on split replies

- README.md
@ekolker can you give this a fairly thorough looking over? I suspect I'm missing information re what the pins can do.
Also not certain what is/isn't all the way implemented; @kevinmehall can you note if I've documented anything that doesn't exist/work that way yet?
> more complete hardware API docs

- node/.jscsrc
- node/.jshintrc
- node/Gruntfile.js
- node/package.json
- None of these will pass
- This changeset will not fix any issues. A set of followup branches will implement the necessary fixes
> Introduce the same code quality enforcement system that t2-cli uses.

- node/tessel.js
Blocked by https://github.com/tessel/t2-firmware/pull/56
Once that lands, this will apply cleanly
> Enforce jscs rules: passing (Order: 2)

- node/tessel.js
- node/test/unit/tessel.js
Blocked by https://github.com/tessel/t2-firmware/pull/57
Once that lands, this will apply cleanly
> Make Tessel firmware testable; basic unit tests for Tessel & Port (Order: 3)

- node/tessel.js
- node/test/unit/tessel.js
Smoke tests completed: 
- digital read on port A, pins 0, 1, 2, 3, 4, 5, 6, 7
- digital read on port B, pins 0, 1, 2, 3, 4, 5, 6, 7
- analog read on port A, pins 4, 7
- analog read on port B, pins 0, 1, 2, 3, 4, 5, 6, 7
(Manually)
> Restore REPLY_HIGH, REPLY_LOW handling. Fixes gh-63

- README.md
> add brew install dfu-util instructions

- node/tessel-export.js
I've had this running on both of my Tessels for a week and it's been working with 100% reliability for me during development and rapid iteration.
> Close any initialized port on SIGINT

- firmware/main.c
This is a stop gap PR to give better visibility into when OpenWRT is booting (we have a big hackathon tomorrow). It's a hacky but the legitimate way to do it is in progress [here](https://github.com/tessel/t2-firmware/pull/99).
To test:
- put T2 into bootloader mode by plugging it in while holding down the button
- run `make` on this branch
- run `dfu-util -aFlash -l -D build/firmware.bin` in your terminal
- watch the blinking lights.
> Jon ugly leds

- node/tessel-export.js
- node/test/unit/tessel.js
- Enforces LED initial state to off/low/0 (this hands over control to the user)
- Implements a `Tessel.LEDs` collection that exposes leds at numeric indices, that initialize only on _first_ access.
- Adheres to existing tested semantics
For some context, I crafted this changeset after I started reviewing the t2-start site. The [first "blinky" example](http://tessel.github.io/t2-start/blinky.html) is overcomplicated for what it aims to teach: 
```js
// Import the interface to Tessel hardware
// Set the led pins as outputs
var led1 = tessel.led[2];
var led2 = tessel.led[3];
// Set initial LED states
led1.output(1);
led2.output(0);
setInterval(function () {
console.log("I'm blinking! (Press CTRL + C to stop)");
// Toggle the led states
led1.toggle(); …
```
> LED(s): Lazy initialization; reduce file IO by storing state internally.

- node/tessel-export.js
- node/test/unit/tessel.js
Fixes #109 
I would love feedback on these tests, as well as the potential method name and interaction.
> [WIP] Adds 'LED.getState' method to tessel node module

- README.md
@r? @johnnyman727 @kevinmehall
> update to update instructions

- firmware/firmware.h
- firmware/main.c
- firmware/usb.c
> Ensures USB comms are not forwarded to OpenWRT before it has booted

- boot/usb.c
- firmware/usb.c
@tcr is this appropriate naming convention? As opposed to "Tessel Project"
> s/ "Technical Machine" "Tessel"

- node/tessel-export.js
- node/test/unit/tessel.js
> Allow new UART and SPI interface creations

- common/board.h
- firmware/main.c
Fixes #131 and #122.
TODO:
To Test: 
```
make; python scripts/boot.py; sleep 1; dfu-util -aFlash -d 1209:7551 -D build/firmware.bin
```
> Creates "breathing LED" effect for boot up

- firmware/port.c
- node/tessel-export.js
- node/test/unit/tessel.js
Intended to be compatible [with T1 Firmware](https://github.com/tessel/t1-docs/blob/master/hardware-api.md#api-pin-pull-mode).
To test:
* Build and flash the firmware (see instructions in README.md)
* Transfer the revised `tessel-export.js` to your Tessel (`scp -i ~/.tessel/id_rsa node/tessel-export.js root@YOUR_TESSEL_NAME.local:/usr/lib/node/tessel-export.js`)
Use the API as described in that T1 doc.
```.js
var pin = tessel.port.A.pin[2];
pin.mode('pullup', function() {
pin.read(function(err, val) {
console.log('pull up val', val) // 1
pin.mode('pulldown', function() => {
pin.read(function(err, val) {
console.log('pull down val', val); // 0
});
});
});
})
```
Fixes #145.
> Adds support for pull resistors

- node/package.json
- node/tessel-export.js
- node/test/unit/tessel.js
Fixes #129 
This build covers a proposed Network Wifi API. The API is inspired by https://github.com/tessel/t1-docs/blob/master/wifi.md#connecting-to-wifi-from-js .
Example:
```js
// when "connect" event fires, log the returned settings
tessel.network.wifi.on('connect', console.log.bind(console));
// connect to wifi network
tessel.network.wifi.connect({
ssid: 'MyNetwork',
password: 'MyPassword',
security: 'psk2'
}, function(error, settings) {
if (error) {
throw error;
}
// logs the settings and network info returned, same info as "t2 wifi" when connected
console.log(settings);
// logs true
console.log(tessel.network.wifi.isConnected);
});
```
> Network API

- firmware/firmware.h
- firmware/usb.c
- scripts/flash.py
~~TODO: Figure out why it's not actually rebooting after pulling the reset line low and then high.~~
> Makes the python flashing code more reliable

- common.mk
- common/board.h
- common/hw.h
- common/pwm.c
- common/util.h
- firmware/main.c
- firmware/port.c
- node/tessel-export.js
- node/test/unit/tessel.js
Pending API comments on https://github.com/tessel/t2-firmware/issues/21.
Fixes #21.
Docs at https://github.com/tessel/t2-docs/pull/46.
> [WIP] Adds PWM capabilities and tests

- node/tessel-export.js
- node/test/unit/tessel.js
> I2C: corrections to frequency to match reality.

- node/tessel-export.js
- node/test/unit/tessel.js
Fixes #160
Includes some formatting changes after running through `grunt`.
> Adds Access Point event aliases

- firmware/port.c
- node/tessel-export.js
- node/test/unit/tessel.js
> Interrupts: deliver the state of the pin for change events. Closes gh-152

- .travis.yml
> ci: add node.js 5

- node/tessel-export.js
- node/test/unit/tessel.js
NOTES:
The `mode` and `port` arguments that are seen in the t1-firmware version of the built-in hardware APIs are actually never used.
- https://github.com/tessel/climate-si7005/blob/master/index.js#L80
- https://github.com/tessel/climate-si7020/blob/master/index.js#L56
- https://github.com/tessel/servo-pca9685/blob/master/index.js#L62
- https://github.com/tessel/accel-mma84/blob/master/index.js#L40
Additionally, there are no places where Tessel.I2C expects/requires params object containing `addr` or `freq`, so these have been renamed `address` and `frequency`
> I2C: Allow setting the frequency at initialization

- node/tessel-export.js
- node/test/unit/tessel.js
Only fix. I couldnt find a proper location at unit test file to test the case.
> Fixes #176: read buffer instead string.

- node/test/unit/tessel.js
> Add lower value test for .analogRead().

- node/tessel-export.js
- node/test/unit/tessel.js
- adds `close` method to Tessel.Port.prototype
- updates Tessel.prototype.close to delegate to Tessel.Port.prototype.close
1. Pull this branch local
2. With a T2 connected via LAN, run: 
```
scp -i /PATH/TO/t2-firmware/node/tessel-export.js root@[NAME OF YOUR TESSEL].local:/usr/lib/node/tessel-export.js
```
(make the appropriate changes)
3. Create a new project: 
```
t2 init
```
4. Paste this into the `index.js` file: 
```js
var ports = ['A', 'B'];
function shutdown() {
if (ports.length) {
var port = ports.shift();
console.log(`In 2 seconds, I will close Port ${port}`);
setTimeout(() => {
tessel.port[port].close();
shutdown();
}, 2000);
} else {
console.log('All ports closed, process exiting');
process.exit();
}
}
shutdown();
```
Expected outcome: 
```
$ t2 …
```
> Tessel.Port: allow intentional port closing

- firmware/port.c
Fixes https://github.com/tessel/rfid-pn532/issues/30.
This fixes the following case the case where an interrupt is set as an interrupt, unset as an interrupt, and then set as an interrupt again. The final interrupt set was reportedly hit when, in reality, it was not.
What was happening was that when the interrupt was being cleared, it was set back as a GPIO but when it was set for the final time, [it was configured as an interrupt before setting the pin mux as an interrupt](https://github.com/tessel/t2-firmware/blob/master/firmware/port.c#L389). The resulted in the interrupt being fired depending on the impedence state of the pin.
This PR fixes that by explicitly setting the pin mux *before* setting the interrupt when we are setting an active interrupt state and the opposite order when …
> Fix order of mux and extint set

- node/tessel-export.js
- node/test/unit/tessel.js
Fixes an error reported in the forums:
https://forums.tessel.io/t/wifi-error-since-latest-update/2717
> fix(wifi.connect): checks for encryption object

- node/tessel-export.js
> Change all inline no-ops to use shared no-op function object

- node/tessel-export.js
- node/tessel.js
- node/test/unit/tessel.js
Remaining coverage needed for:
- Tessel.AP
- Tessel.Wifi
Notes: once @HipsterBrown completes coverage for the above, I have a mostly completed patch set for modernizing the codebase. I'm holding off on that until we have 100% coverage to avoid any issues arising during that transition.
> Improving test coverage

- node/tessel-export.js
- node/test/unit/tessel.js
> Test Coverage of Tessel.Wifi and Tessel.AP

- node/tessel-export.js
- node/test/unit/tessel.js
All test changes are specifically: 
- syntactic updates
- changes to account for the non-configurability of class prototypes
> Migrate to modern ES 

- node/tessel-export.js
- node/test/unit/tessel.js
Without this change opens wifi while scanning at AP mode.
Tried this code at Tessel manually. Did not build the firmware.
@rwaldron @HipsterBrown Can you please review and merge ? This is urgent for me.
> Able to scan at AP mode
